nb_item: 50000
pool_add_random_low: 10
pool_add_random_high: 50
pool_keep_best: 200
pool_size: 500
rounds: 500
sack_max_weight: 5000000
value_max: 100000
value_min: 1
weight_max: 100000
weight_min: 1
